// DEVELOPMENT PLACEHOLDER VALUES - NOT FOR PRODUCTION USE
// This file contains dummy Firebase configuration values for development purposes only.
// 
// To use real Firebase:
// 1. Create a Firebase project at https://console.firebase.google.com/
// 2. Add your apps (Android, iOS, Web)
// 3. Download the configuration files
// 4. Replace these placeholder values with your actual Firebase project values
// 5. Uncomment Firebase initialization in main.dart and app_state.dart
//
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // For development purposes, using a minimal configuration
  // This will allow the app to run without Firebase errors
  // In production, replace these with your actual Firebase project values
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForDevelopmentOnly',
    appId: '1:123456789012:web:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'swiftlyft-dev',
    authDomain: 'swiftlyft-dev.firebaseapp.com',
    storageBucket: 'swiftlyft-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForDevelopmentOnly',
    appId: '1:123456789012:android:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'swiftlyft-dev',
    storageBucket: 'swiftlyft-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForDevelopmentOnly',
    appId: '1:123456789012:ios:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'swiftlyft-dev',
    storageBucket: 'swiftlyft-dev.appspot.com',
    iosClientId: '123456789012-abcdefghijklmnop.apps.googleusercontent.com',
    iosBundleId: 'com.example.swiftlyft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForDevelopmentOnly',
    appId: '1:123456789012:ios:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'swiftlyft-dev',
    storageBucket: 'swiftlyft-dev.appspot.com',
    iosClientId: '123456789012-abcdefghijklmnop.apps.googleusercontent.com',
    iosBundleId: 'com.example.swiftlyft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForDevelopmentOnly',
    appId: '1:123456789012:web:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'swiftlyft-dev',
    storageBucket: 'swiftlyft-dev.appspot.com',
  );
} 